kind: Service
apiVersion: v1
metadata:
  name: coffee-society-product-catalog
  labels:
    app: coffee-society-product-catalog
spec:
  type: ClusterIP
  selector:
    app: coffee-society-product-catalog
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
