kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffee-society-member
  labels:
    app: coffee-society-member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-society-member
  template:
    metadata:
      labels:
        app: coffee-society-member
    spec:
      containers:
      - name: coffee-society-member
        image: csms/coffee-society-member:latest
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DB
          value: "admin"
        - name: AXON_HOST
          value: "axon"
        - name: LDAP_URL
          value: "ldap://ldap:389"
        - name: LDAP_DOMAIN
          value: "ou=people,dc=planetexpress,dc=com"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5